# Generated by Django 4.2.3 on 2024-05-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
